// Person 1: Responsible for shared platform constants and status enums.
const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  CONFIRMING: 'CONFIRMING',
  PAID: 'PAID',
  SETTLEMENT_PENDING: 'SETTLEMENT_PENDING',
  SETTLED: 'SETTLED',
  EXPIRED: 'EXPIRED',
  FAILED: 'FAILED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
});

const PAYMENT_STATUS = Object.freeze({
  DETECTED: 'DETECTED',
  VERIFYING: 'VERIFYING',
  CONFIRMING: 'CONFIRMING',
  CONFIRMED: 'CONFIRMED',
  UNDERPAID: 'UNDERPAID',
  OVERPAID: 'OVERPAID',
  REJECTED: 'REJECTED',
  DUPLICATE: 'DUPLICATE',
  FAILED: 'FAILED'
});

const SETTLEMENT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
});

const MERCHANT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED'
});

const USER_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT'
});

const NETWORKS = Object.freeze({
  SEPOLIA: 'SEPOLIA',
  MAINNET: 'MAINNET'
});

module.exports = {
  INVOICE_STATUS,
  PAYMENT_STATUS,
  SETTLEMENT_STATUS,
  MERCHANT_STATUS,
  USER_ROLES,
  NETWORKS
};